/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;
import org.junit.jupiter.api.Test;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;

import static org.junit.jupiter.api.Assertions.*;


class AppTest {
    @Test
    public void getQuoteFromFilTest() {
        String testAuthor = "Louis Armstrong";
        String testText = "“What we play is life.“";
        Object testObject = new Quotes(null, testAuthor, "0", testText);
        System.out.println(testObject);
        String filePath = "./src/test/resources/recentquotesTest.json";
        ArrayList<Quotes> output = App.getQuotesFromFile(filePath);
        assertNotNull(output);
        assertEquals(output.get(6).getAuthor(), testAuthor);




    }
    @Test
    public void getQuoteFromApiTest(){
        String testUrl = "http://api.forismatic.com/api/1.0/?method=getQuote&format=json&lang=en";
        System.out.println("out"+App.sendGetRequest(testUrl));
        assertNotNull(App.sendGetRequest(testUrl));

    }


}

